const SUPABASE_URL="https://jhipuzlapddqvpmypulc.supabase.co",SUPABASE_KEY="sb_publishable_3zOehYy0-IpKXbbM7gHPWw_OiAQ81Aq";
const book=document.getElementById("book"),account=document.getElementById("account"),status=document.getElementById("status");
let accessToken=sessionStorage.getItem("gis_access_token"),adminEmail=sessionStorage.getItem("gis_admin_email");
async function rest(path,opt={},token=SUPABASE_KEY){const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{...opt,headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${token}`,"Content-Type":"application/json",...(opt.headers||{})}});const t=await r.text();if(!r.ok)throw Error(t||`HTTP ${r.status}`);return t?JSON.parse(t):[]}
async function storageUpload(file,token){const path=encodeURIComponent(file.name);const r=await fetch(`${SUPABASE_URL}/storage/v1/object/kml-files/${path}`,{method:"POST",headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${token}`,"Content-Type":file.type||"application/vnd.google-earth.kml+xml","x-upsert":"false"},body:file});const t=await r.text();if(!r.ok)throw Error(t||`Storage upload failed (HTTP ${r.status})`);return t?JSON.parse(t):{}}
async function storageDelete(bookNo,token){const path=encodeURIComponent(bookNo+".kml");const r=await fetch(`${SUPABASE_URL}/storage/v1/object/kml-files/${path}`,{method:"DELETE",headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${token}`}});const t=await r.text();if(!r.ok)throw Error(t||`Storage delete failed (HTTP ${r.status})`);return t?JSON.parse(t):{}}
async function loadBooks(){try{const d=await rest('locations?select=%22Book%20No%22&order=%22Book%20No%22.asc');const v=[...new Set(d.map(x=>x["Book No"]).filter(Boolean))];book.innerHTML='<option value="">Select Book No</option>';v.forEach(x=>book.add(new Option(x,x)));}catch(e){status.textContent="Book load error: "+e.message}}
book.onchange=async()=>{account.innerHTML="<option>Loading...</option>";account.disabled=true;if(!book.value)return;try{const d=await rest(`locations?select=%22Account%20No%22&%22Book%20No%22=eq.${encodeURIComponent(book.value)}&order=%22Account%20No%22.asc`);account.innerHTML='<option value="">Select Account No</option>';[...new Set(d.map(x=>x["Account No"]).filter(Boolean))].forEach(x=>account.add(new Option(x,x)));account.disabled=false}catch(e){status.textContent=e.message}};
document.getElementById("search").onclick=async()=>{if(!book.value||!account.value)return status.textContent="Select Book No and Account No.";try{const d=await rest(`locations?select=%22Latitude%22,%22Longitude%22&%22Book%20No%22=eq.${encodeURIComponent(book.value)}&%22Account%20No%22=eq.${encodeURIComponent(account.value)}&limit=1`);if(!d.length)throw Error("Location not found");window.open(`https://www.google.com/maps/search/?api=1&query=${d[0]["Latitude"]},${d[0]["Longitude"]}`,"_blank")}catch(e){status.textContent=e.message}};
const login=document.getElementById("login"),admin=document.getElementById("admin"),upstatus=document.getElementById("upstatus"),delBook=document.getElementById("deleteBook"),delStatus=document.getElementById("deleteStatus");
function show(v){login.hidden=v;admin.hidden=!v;if(v){document.getElementById("who").textContent="Logged in: "+adminEmail;loadAdminBooks()}}
document.getElementById("loginBtn").onclick=async()=>{upstatus.textContent="Logging in...";try{const r=await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=password`,{method:"POST",headers:{apikey:SUPABASE_KEY,"Content-Type":"application/json"},body:JSON.stringify({email:email.value.trim(),password:pass.value})});const d=await r.json();if(!r.ok)throw Error(d.error_description||d.msg||"Login failed");accessToken=d.access_token;adminEmail=email.value.trim();sessionStorage.setItem("gis_access_token",accessToken);sessionStorage.setItem("gis_admin_email",adminEmail);show(true);upstatus.textContent="Admin login successful."}catch(e){upstatus.textContent="Login error: "+e.message}};
document.getElementById("logout").onclick=()=>{accessToken=null;sessionStorage.clear();show(false)};
function parseKml(t,b){const x=new DOMParser().parseFromString(t,"application/xml"),o=[];if(x.querySelector("parsererror"))throw Error("Invalid KML/XML");[...x.getElementsByTagName("Placemark")].forEach(p=>{let a="";[...p.getElementsByTagName("SimpleData")].some(n=>{let k=(n.getAttribute("name")||"").toLowerCase(),v=n.textContent.trim();if(/account|consumer|customer|acct|acc/.test(k)&&v){a=v;return true}return false});if(!a)a=(p.getElementsByTagName("name")[0]?.textContent||"").trim();let c=p.getElementsByTagName("coordinates")[0]?.textContent.trim().split(/\s+/)[0];if(a&&c){let q=c.split(","),lon=+q[0],lat=+q[1];if(Number.isFinite(lat)&&Number.isFinite(lon))o.push({"Book No":b,"Account No":a,"Latitude":lat,"Longitude":lon})}});return o}
document.getElementById("upload").onclick=async()=>{let f=document.getElementById("file").files[0];if(!f)return upstatus.textContent="Select a KML file.";if(!accessToken)return upstatus.textContent="Please login as Admin first.";try{let b=f.name.replace(/\.[^.]+$/g,"").trim();let rows=parseKml(await f.text(),b);if(!rows.length)throw Error("No locations found");upstatus.textContent=`Replacing Book No ${b}...`;
// Remove the old database rows first so the new KML becomes the current version.
await rest(`locations?%22Book%20No%22=eq.${encodeURIComponent(b)}`,{method:"DELETE",headers:{Prefer:"return=minimal"}},accessToken);
// Remove the previous KML if it exists. A missing file is harmless.
try{await storageDelete(b,accessToken)}catch(oldStorageErr){if(!/404|not found/i.test(oldStorageErr.message))throw oldStorageErr}
upstatus.textContent=`Uploading new ${f.name} to Storage...`;
await storageUpload(f,accessToken);
upstatus.textContent=`Storage upload complete. Saving ${rows.length} locations...`;
for(let i=0;i<rows.length;i+=200){await rest("locations",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify(rows.slice(i,i+200))},accessToken)}
upstatus.textContent=`Success! Book No ${b} replaced: Storage updated + ${rows.length} locations saved.`;
document.getElementById("file").value="";loadBooks();loadAdminBooks()}catch(e){upstatus.textContent="Upload error: "+e.message}};
async function loadAdminBooks(){try{let d=await rest('locations?select=%22Book%20No%22&order=%22Book%20No%22.asc',{},accessToken),v=[...new Set(d.map(x=>x["Book No"]).filter(Boolean))];delBook.innerHTML='<option value="">Select Book No</option>';v.forEach(x=>delBook.add(new Option(x,x)))}catch(e){delStatus.textContent="List error: "+e.message}}
document.getElementById("deleteBtn").onclick=async()=>{let b=delBook.value;if(!b)return delStatus.textContent="Select Book No first.";if(!confirm(`Delete Book No ${b} from locations AND its KML file from Storage? This cannot be undone.`))return;delStatus.textContent="Deleting locations and KML file...";try{await rest(`locations?%22Book%20No%22=eq.${encodeURIComponent(b)}`,{method:"DELETE",headers:{Prefer:"return=minimal"}},accessToken);try{await storageDelete(b,accessToken)}catch(storageErr){delStatus.textContent=`Locations deleted, but Storage file could not be deleted: ${storageErr.message}`;await loadBooks();await loadAdminBooks();return}delStatus.textContent=`Book No ${b} and its KML file deleted successfully.`;await loadBooks();await loadAdminBooks()}catch(e){delStatus.textContent="Delete error: "+e.message}};
show(!!accessToken);loadBooks();